splunk:
  conf:
    serverclass:
      directory: /opt/splunk/etc/system/local/
      content:
        serverClass:normal:app:normal:
          restartSplunkWeb: 0
          restartSplunkd: 1
          stateOnClient: enabled

        serverClass:unlimited:app:unlimited-speed:
          restartSplunkWeb: 0
          restartSplunkd: 1
          stateOnClient: enabled

        serverClass:double:app:double-speed:
          restartSplunkWeb: 0
          restartSplunkd: 1
          stateOnClient: enabled

        serverClass:all-uf:app:forward-to-so1:
          restartSplunkWeb: 0
          restartSplunkd: 1
          stateOnClient: enabled

        serverClass:unlimited:
          whitelist.0: uf0

        serverClass:normal:
          whitelist.0: uf1

        serverClass:double:
          whitelist.0: uf2

        serverClass:all-uf:
          whitelist.0: uf*