splunk:
  hec:
    enable: True
    ssl: True
    token: abcd-1234-efgh-5678
    port: 8088
  conf:
    indexes:
      directory: /opt/splunk/etc/apps/search/local/
      content:
        cust0:
          homePath: $SPLUNK_DB/cust0/db
          coldPath: $SPLUNK_DB/cust0/colddb
          thawedPath: $SPLUNK_DB/cust0/thaweddb
          maxHotBuckets: 1
        cust1:
          homePath: $SPLUNK_DB/cust1/db
          coldPath: $SPLUNK_DB/cust1/colddb
          thawedPath: $SPLUNK_DB/cust1/thaweddb
          maxHotBuckets: 1
        cust2:
          homePath: $SPLUNK_DB/cust2/db
          coldPath: $SPLUNK_DB/cust2/colddb
          thawedPath: $SPLUNK_DB/cust2/thaweddb
          maxHotBuckets: 1
    props:
      directory: /opt/splunk/etc/apps/search/local/
      content:
        heure:
          DATETIME_CONFIG:
          LINE_BREAKER: (\r\n+)
          NO_BINARY_CHECK: true
          category: Custom
          description: Generated hour
          pulldown_type: 1
          TRANSFORMS-cust: addcust

    transforms:
      directory: /opt/splunk/etc/apps/search/local/
      content:
        addcust:
          SOURCE_KEY: cust
          REGEX: (.*)
          FORMAT: cust::$1
          WRITE_META: true

    fields:
      directory: /opt/splunk/etc/apps/search/local/
      content:
        cust:
          INDEXED: true
